# .streamlit/secrets.toml

OPENAI_API_KEY = "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"